[package]
name = "crystal-colors"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.5.3"
rocket = "0.5.0"
rocket_ws = "0.1.0"
shuttle-rocket = "0.48.0"
shuttle-runtime = "0.48.0"
tokio = "1.26.0"
